// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAB4h1SGGuymfy8bGz1jmKjQ03oK9jDPHw',
    appId: '1:582051428490:web:cbdb35caf7766539049573',
    messagingSenderId: '582051428490',
    projectId: 'pandaloginsignup',
    authDomain: 'pandaloginsignup.firebaseapp.com',
    storageBucket: 'pandaloginsignup.firebasestorage.app',
    measurementId: 'G-KM69Y2466S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR5RiSH0VAcxS_6I-C8epfv2ejgZf89sk',
    appId: '1:582051428490:android:fb7576ade9406338049573',
    messagingSenderId: '582051428490',
    projectId: 'pandaloginsignup',
    storageBucket: 'pandaloginsignup.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDEUu74xLt2kbaql5xZISeHyARDSnuIQgc',
    appId: '1:582051428490:ios:dad03304143151a8049573',
    messagingSenderId: '582051428490',
    projectId: 'pandaloginsignup',
    storageBucket: 'pandaloginsignup.firebasestorage.app',
    iosBundleId: 'com.example.pandaLogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDEUu74xLt2kbaql5xZISeHyARDSnuIQgc',
    appId: '1:582051428490:ios:dad03304143151a8049573',
    messagingSenderId: '582051428490',
    projectId: 'pandaloginsignup',
    storageBucket: 'pandaloginsignup.firebasestorage.app',
    iosBundleId: 'com.example.pandaLogin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAB4h1SGGuymfy8bGz1jmKjQ03oK9jDPHw',
    appId: '1:582051428490:web:ac6de079e2658a05049573',
    messagingSenderId: '582051428490',
    projectId: 'pandaloginsignup',
    authDomain: 'pandaloginsignup.firebaseapp.com',
    storageBucket: 'pandaloginsignup.firebasestorage.app',
    measurementId: 'G-3BRCSREBZ7',
  );
}
